### ISSUE TITLE
Live demo white screen

### ISSUE THREAD

**Issue by atuonufure** [beda-software/sdc-ide#65]
When trying to open the live demo http://sdc.beda.software/ a white screen is displayed.
White screen should be replaced with a text information about launch mechanism, default login and password and a link to run ide on top of EMR https://sdc.beda.software?client=sdc-ide

![image](https://github.com/beda-software/sdc-ide/assets/70858867/543c1803-0a88-4f54-bf42-c65b5576d425)

**Comment by ruscoder** [comment]
Looks it's not relevant anymore, closing the issue
