### ISSUE TITLE
Unable to see in what question the fhirpath error occured

### ISSUE THREAD

**Issue by mlaletina95** [beda-software/sdc-ide#80]
I have a questionnaire with 5000+ lines where I have tens of expressions and it's incredible difficult to understand in what question the error has occured. See the attached screenshot. 

Expected behavior:
- The linkId of the question is displayed alongside with the error in the console

<img width="1262" alt="Снимок экрана 2024-10-08 в 23 39 50" src="https://github.com/user-attachments/assets/cefbfcf5-7c8f-49d6-b8a8-4148d710d9e3">

**Comment by ruscoder** [comment]
I've added verbose information to the error about linkId and the field name (variable, calculatedExpression, enableWhenExpresson)

<img width="981" alt="Screenshot 2024-10-09 at 21 14 13" src="https://github.com/user-attachments/assets/44c65d6a-3fbe-41cf-88ae-fe59a3113057">
